export const PHONE_DATA_REQUEST='PHONE_DATA_REQUEST';
export const PHONE_DATA_SUCCESS='PHONE_DATA_SUCCESS';
export const PHONE_DATA_FAILURE='PHONE_DATA_FAILURE';

export const LAPTOP_DATA_REQUEST='LAPTOP_DATA_REQUEST';
export const LAPTOP_DATA_SUCCESS='LAPTOP_DATA_SUCCESS';
export const LAPTOP_DATA_FAILURE='LAPTOP_DATA_FAILURE';

export const TV_DATA_REQUEST='TV_DATA_REQUEST';
export const TV_DATA_SUCCESS='TV_DATA_SUCCESS';
export const TV_DATA_FAILURE='TV_DATA_FAILURE';


